import json
import os
import datetime
import re
import urllib.parse
from datetime import timedelta
from icalendar import Calendar, Event

class AllergenChecker:
    def __init__(self, data_path="data/allergens.json"):
        self.allergens = []
        self._load_rules(data_path)

    def _load_rules(self, path):
        """加载本地过敏原规则库"""
        try:
            if os.path.exists(path):
                with open(path, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    self.allergens = data.get("allergens", [])
            else:
                print(f"Warning: Allergen rule file not found at {path}")
        except Exception as e:
            print(f"Error loading allergen rules: {e}")

    def check_risks(self, ingredients):
        """
        语义匹配成分列表
        返回: [{"allergen": "花生", "severity": "high", "warning": "..."}]
        """
        detected_risks = []
        if not ingredients:
            return detected_risks

        # 归一化输入成分
        normalized_ingredients = [str(i).lower().strip() for i in ingredients]

        for rule in self.allergens:
            rule_name = rule["name"]
            aliases = [a.lower() for a in rule.get("aliases", [])]
            aliases.append(rule_name.lower())
            
            # 检查每个输入成分是否包含任何别名
            for ingredient in normalized_ingredients:
                for alias in aliases:
                    if alias in ingredient:
                        detected_risks.append({
                            "allergen": rule_name,
                            "severity": rule["severity"],
                            "warning": rule["warning_msg"],
                            "source": ingredient # 触发匹配的原始成分
                        })
                        break # 一个规则只需匹配一次
                else:
                    continue
                break 

        return detected_risks

class EventParser:
    def __init__(self):
        pass

    def parse_datetime(self, time_str):
        """
        尝试将自然语言或非标准时间转换为 datetime 对象
        支持格式: "YYYY-MM-DD HH:MM", "YYYY/MM/DD HH:MM"
        """
        try:
            # 简单清理
            clean_str = time_str.replace("：", ":").strip()
            
            # 尝试常见格式
            formats = [
                "%Y-%m-%d %H:%M",
                "%Y/%m/%d %H:%M",
                "%Y-%m-%d %H:%M:%S",
                "%Y年%m月%d日 %H:%M",
                "%m-%d %H:%M" # 处理不带年份的情况 (假设今年)
            ]
            
            dt = None
            for fmt in formats:
                try:
                    dt = datetime.datetime.strptime(clean_str, fmt)
                    # 如果没有年份，补全为今年
                    if dt.year == 1900: 
                        dt = dt.replace(year=datetime.datetime.now().year)
                    break
                except ValueError:
                    continue
            
            return dt
        except Exception as e:
            print(f"Time Parse Error: {e}")
            return None

    def generate_ics_structure(self, event_name, start_time, location, description=""):
        """准备 .ics 生成所需的数据结构"""
        if not start_time:
            return None
            
        end_time = start_time + timedelta(hours=1)
        
        return {
            "summary": event_name,
            "dtstart": start_time,
            "dtend": end_time,
            "location": location,
            "description": description
        }

    def generate_google_calendar_link(self, event_data):
        """生成 Google Calendar URL"""
        if not event_data:
            return None
            
        start_str = event_data['dtstart'].strftime("%Y%m%dT%H%M00")
        end_str = event_data['dtend'].strftime("%Y%m%dT%H%M00")
        
        params = {
            "action": "TEMPLATE",
            "text": event_data['summary'],
            "dates": f"{start_str}/{end_str}",
            "location": event_data['location'],
            "details": f"{event_data['description']} (By LensFlow)"
        }
        return f"https://calendar.google.com/calendar/render?{urllib.parse.urlencode(params)}"
    
    def generate_ics_file_content(self, event_data):
        """
        生成 .ics 文件内容 (字节流)
        需要安装: pip install icalendar
        """
        if not event_data:
            return None
            
        cal = Calendar()
        cal.add('prodid', '-//LensFlow AI Assistant//mxm.dk//')
        cal.add('version', '2.0')

        event = Event()
        event.add('summary', event_data['summary'])
        event.add('dtstart', event_data['dtstart'])
        event.add('dtend', event_data['dtend'])
        event.add('location', event_data['location'])
        event.add('description', f"{event_data['description']} (Generated by LensFlow)")
        
        cal.add_component(event)
        
        return cal.to_ical()

class LogicEngine:
    def __init__(self):
        self.allergen_checker = AllergenChecker()
        self.event_parser = EventParser()


    def analyze_health_risk(self, ingredients):
        """
        代理到 AllergenChecker
        返回风险名称列表 (为了兼容旧接口)
        """
        risks = self.allergen_checker.check_risks(ingredients)
        # 提取高风险项
        return [r["allergen"] for r in risks]
    
    def get_risk_details(self, ingredients):
        """获取详细风险信息"""
        return self.allergen_checker.check_risks(ingredients)

    def parse_calendar_data(self, event_name, time_str, location):
        """
        代理到 EventParser
        返回 Google Calendar Link
        """
        dt = self.event_parser.parse_datetime(time_str)
        if dt:
            event_data = self.event_parser.generate_ics_structure(
                event_name, dt, location
            )
            return self.event_parser.generate_google_calendar_link(event_data)
        return None

    def get_ics_content(self, event_name, time_str, location):
        """
        生成 .ics 文件内容
        """
        dt = self.event_parser.parse_datetime(time_str)
        if dt:
            event_data = self.event_parser.generate_ics_structure(
                event_name, dt, location
            )
            return self.event_parser.generate_ics_file_content(event_data)
        return None

